### ISSUE TITLE
Use let instead of var

### ISSUE THREAD

**Issue by BookOwl** [liam4/pythonic-javascript#1]

**Comment by towerofnix** [comment]
I'd normally do that but you might notice this:

``` python
for x in range(0, 8):
  pass

print(x) # -> 7
```

I might use `let` anyways, though, because it's pretty much always the better choice. :package:

**Comment by towerofnix** [comment]
Okay, fixed by b30d249e75a908f53fa64a8ae029514a30a0a1d0. Feel free to tell me if I missed anything.
