### ISSUE TITLE
Don't assume perfect browsers

### ISSUE THREAD

**Issue by ghost** [liam4/pythonic-javascript#2]
Just don't

**Comment by towerofnix** [comment]
Nobody has perfect browsers, so you should always transpile

WHICH IS WHAT I INCLUDED IN THE NOTICE AT THE TOP

:)

edit: I'll improve the notice though

**Comment by ghost** [comment]
or you can not use transpilers and use cross browser code in the first place :ok_hand:

**Comment by towerofnix** [comment]
cross browser code is baaaad. code that works with the _official_ spec is gooooood.

:P
