### ISSUE TITLE
"6 is returned"

### ISSUE THREAD

**Issue by jeandrek** [liam4/pythonic-javascript#4]
``` py
@wrapper
def my_function(x):
    return x * 2

my_function(6) # "Hey, you called me!" gets printed and 6 is returned
```

12 should be returned, because 6 \* 2 = 12. Mathematics!

**Comment by towerofnix** [comment]
derrrrrrrp

**Comment by jeandrek** [comment]
Oh, in the corresponding JS example it's called with 3 rather than 6.

**Comment by towerofnix** [comment]
![screen shot 2016-04-07 at 9 07 54 pm](https://cloud.githubusercontent.com/assets/9948030/14370473/d0a0006e-fd04-11e5-92eb-1a97e1c0e02e.png)
fixed in exactly 42 seconds. :P

**Comment by jeandrek** [comment]
Since the issue was opened? Wow.

**Comment by towerofnix** [comment]
Actually, since I said "derrrp" but that was hardly a minute maybe after the issue was opened :P
